language: julia

os:
  - windows
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3

notifications:
  email: false

matrix:
  allow_failures:
    - julia: 1.3

before_install:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install make; fi

script:
  - travis_wait 40 julia --color=yes -e 'using Pkg; if VERSION >= v"1.1.0-rc1"; Pkg.build(verbose=true); else Pkg.build(); end';
  - julia --check-bounds=yes --color=yes -e 'using Pkg; Pkg.test(coverage=false);';