name = "Z3"
uuid = "06b161dc-0161-11ea-0f74-41f836f4024b"
authors = ["Andreas Humenberger <ahumenberger@gmail.com>"]
version = "0.3.0"

[deps]
CxxWrap = "1f15a43c-97ca-5a2a-ae31-89f07a497df4"

[compat]
julia = "1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
